// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/advisor-ui/LiquidGlass.tsx": () => import("../components/mockups/advisor-ui/LiquidGlass.tsx"),
  "./components/mockups/advisor-ui/NeonGrid.tsx": () => import("../components/mockups/advisor-ui/NeonGrid.tsx"),
  "./components/mockups/advisor-ui/NeuralPulse.tsx": () => import("../components/mockups/advisor-ui/NeuralPulse.tsx")
};
